const fs = require('node:fs');
const path = require('node:path');
const { createRequire } = require('node:module');
const webDir = path.resolve(__dirname, '..');
const requireWorker = createRequire(path.join(webDir, '../worker/package.json'));
const { buildSync } = requireWorker('esbuild');

function buildDashboard({ write = true } = {}) {
  const result = buildSync({ entryPoints: [path.join(webDir, 'src/main.jsx')], bundle: true, write: false,
    platform: 'browser', format: 'iife', target: ['es2020'], minify: true, charset: 'utf8',
    jsxFactory: 'React.createElement', jsxFragment: 'React.Fragment', legalComments: 'none',
  });
  const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const shell = fs.readFileSync(path.join(webDir, 'index.html'), 'utf8');
  const palette = JSON.parse(fs.readFileSync(path.join(webDir, 'src/shared/theme.json'), 'utf8'));
  const variables = Object.entries(palette).map(([name, hex]) => {
    const rgb = hex.slice(1).match(/../g).map(value => parseInt(value, 16)).join(' ');
    return `--color-${name}: ${rgb};`;
  }).join('\n');
  const colors = Object.fromEntries(Object.keys(palette).map(name => [name, `rgb(var(--color-${name}) / <alpha-value>)`]));
  const styles = fs.readFileSync(path.join(webDir, 'src/styles.css'), 'utf8');
  const html = '<!-- Generated by web/scripts/build.cjs. Edit web/index.html or web/src/, then npm run build. -->\n'
    + shell.replace('/* APP_COLORS */', JSON.stringify(colors))
      .replace('/* APP_STYLES */', `:root {\n${variables}\n}\n${styles}`).replace('/* APP_SCRIPT */', () => script);
  if (write) fs.writeFileSync(path.join(webDir, 'dashboard.html'), html);
  return html;
}
module.exports = { buildDashboard };
if (require.main === module) { buildDashboard(); console.log('Web modules built → web/dashboard.html'); }
